---
# Configuration file for Travis CI [[https://travis-ci.com]]

language: java

os: linux

dist: bionic

scala:
  - 2.13.5

jdk:
  - openjdk11
  - openjdk15
  - oraclejdk11
  - oraclejdk15

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V


